[palettes.gruvbox_dark]
red = "#fb4934"
maroon = "#cc241d"
peach = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
teal = "#8ec07c"
sky = "#83a598"
sapphire = "#83a598"
blue = "#83a598"
lavender = "#d3869b"
pink = "#d3869b"
mauve = "#d3869b"
rosewater = "#ebdbb2"
flamingo = "#ebdbb2"
text = "#ebdbb2"
subtext1 = "#d5c4a1"
subtext0 = "#bdae93"
overlay2 = "#a89984"
overlay1 = "#928374"
overlay0 = "#7c6f64"
surface2 = "#665c54"
surface1 = "#504945"
surface0 = "#3c3836"
base = "#282828"
mantle = "#1d2021"
crust = "#1d2021"

[palettes.gruvbox_light]
red = "#cc241d"
maroon = "#9d0006"
peach = "#d65d0e"
yellow = "#d79921"
green = "#98971a"
teal = "#689d6a"
sky = "#458588"
sapphire = "#458588"
blue = "#458588"
lavender = "#b16286"
pink = "#b16286"
mauve = "#b16286"
rosewater = "#3c3836"
flamingo = "#3c3836"
text = "#3c3836"
subtext1 = "#504945"
subtext0 = "#665c54"
overlay2 = "#7c6f64"
overlay1 = "#928374"
overlay0 = "#a89984"
surface2 = "#d5c4a1"
surface1 = "#ebdbb2"
surface0 = "#f2e5bc"
base = "#fbf1c7"
mantle = "#f9f5d7"
crust = "#f9f5d7"
