shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.dotenv]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/dotenv"
use = ["dotenv.plugin.zsh"]
